Update to ubi8 python 3.11 image (#819)
* Update to ubi8 python 3.11 image

Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>

* Update base image and update pyhton version

Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>

---------

Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>

diff --git a/prow/Dockerfile b/prow/Dockerfile
--- a/prow/Dockerfile
+++ b/prow/Dockerfile
@@ -1,14 +1,20 @@
-FROM quay.io/openshifttest/python:3.9
+FROM registry.access.redhat.com/ubi9/ubi:latest
 
 LABEL vendor="Red Hat Inc." maintainer="OCP QE Team"
+
+RUN dnf install -y python3.11 python3.11-pip
 
 RUN curl -sSL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux-amd64-rhel8.tar.gz | tar -xvzf -  &&\
     mv kubectl /bin
 
-RUN apt-get update && apt-get install -y gettext-base uuid-runtime jq openssh-client sshpass iputils-ping ncat rsync && \
-    ln -s /bin/bash /usr/bin/bash && /usr/local/bin/python -m pip install --upgrade pip && pip install virtualenv jq
+RUN dnf update -y && dnf install -y gettext util-linux jq openssh-clients sshpass iputils nmap-ncat rsync && \
+    python3.11 -m pip install --upgrade pip && python3.11 -m pip install virtualenv jq
 
-RUN setcap -r /bin/ping
+# Remove capabilities from ping - resolve any symlinks to find actual binary
+RUN PING_BIN=$(readlink -f /usr/bin/ping 2>/dev/null || echo /usr/bin/ping) && \
+    if [ -f "$PING_BIN" ] && [ ! -L "$PING_BIN" ]; then \
+        setcap -r "$PING_BIN" 2>&1 || echo "Warning: Could not remove capabilities from ping (may not be supported)"; \
+    fi
 
 RUN curl -sSL $(curl -sSL https://api.github.com/repos/openshift/rosa/releases/latest | jq -r ".assets[] | select(.name == \"rosa_Linux_x86_64.tar.gz\") | .browser_download_url") | tar xvzf - &&\
     mv rosa /bin && chmod 777 /bin/rosa
